name: Inherited Widget Workshop
type: flutter # Optional
steps:
  - name: Welcome to the InhertiedWidget workshop
    directory: intro
    has_solution: false
  - name: Define the State Data Structure
    directory: step_01
    has_solution: true
  - name: Create a InheritedWidget
    directory: step_02
    has_solution: true
  - name: Create a StatefulWidget around the AppStateScope
    directory: step_03
    has_solution: true
  - name: Insert the AppStateWidget to the widget tree
    directory: step_04
    has_solution: true
  - name: Migrate the ShoppingCartIcon
    directory: step_05
    has_solution: true
  - name: Migrate the ProductList
    directory: step_06
    has_solution: true
  - name: Migrate search TextField
    directory: step_07
    has_solution: true
  - name: The end of workshop
    directory: step_08
    has_solution: false
