name: Github Pages Test

# Accepts 'flutter' or 'dart'
type: flutter

# Configuration for each step
steps:
  - name: Background Colors & Gradients
    directory: intro
    has_solution: false
  - name: Images
    directory: images
    has_solution: false
  - name: Borders
    directory: borders
    has_solution: false
  - name: Rounded Corners
    directory: rounded_corners
    has_solution: false
  - name: Padding
    directory: padding
    has_solution: false
  - name: Shadows
    directory: shadows
    has_solution: false
  - name: Container
    directory: container
    has_solution: false
  - name: Text Styles
    directory: text
    has_solution: false
  - name: Icons
    directory: icons
    has_solution: false
  - name: Put it all together
    directory: outro
    has_solution: false
