# Align with DartPad's analysis rules:
# https://github.com/dart-lang/dart-services/blob/master/lib/src/project_creator.dart#L119

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    use_build_context_synchronously: false
    use_key_in_widget_constructors: false
    use_super_parameters: true
