// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzReVp4StwsA3cA6LYYrQUK49brRcCt94',
    appId: '1:405853262258:web:46d0e760db575d555e14ab',
    messagingSenderId: '405853262258',
    projectId: 'data-control-df283',
    authDomain: 'data-control-df283.firebaseapp.com',
    storageBucket: 'data-control-df283.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyJNU6f1C-i_85lnCYtjLJOpanGUAuKY',
    appId: '1:405853262258:android:711b554e1ecc0cd45e14ab',
    messagingSenderId: '405853262258',
    projectId: 'data-control-df283',
    storageBucket: 'data-control-df283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Puge4XqA24K7RUJXMSR7kfubmNT7XCY',
    appId: '1:405853262258:ios:1e83e5a029cf800e5e14ab',
    messagingSenderId: '405853262258',
    projectId: 'data-control-df283',
    storageBucket: 'data-control-df283.appspot.com',
    iosClientId: '405853262258-7458lp88b8rkt54jblpdrdo2rhm1e2e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Puge4XqA24K7RUJXMSR7kfubmNT7XCY',
    appId: '1:405853262258:ios:505e10f6244f200d5e14ab',
    messagingSenderId: '405853262258',
    projectId: 'data-control-df283',
    storageBucket: 'data-control-df283.appspot.com',
    iosClientId: '405853262258-ba78c9ic5q667nn8aje5fcth08j0m6eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataControl.RunnerTests',
  );
}
