name: Sliver Workshop
type: flutter # Optional
steps:
  - name: Welcome to the Scrolling workshop
    directory: step_01
    has_solution: false
  - name: Create a Lazy Loading ListView
    directory: step_02
    has_solution: true
  - name: Add more to our Lazy ListView
    directory: step_03
    has_solution: true
  - name: Migrate our ListView to a SliverList
    directory: step_04
    has_solution: true
  - name: Add a SliverAppBar
    directory: step_05
    has_solution: true
  - name: Explore the SliverAppBar Further
    directory: step_06
    has_solution: true
  - name: Using the FlexibleSpaceBar
    directory: step_07
    has_solution: true
  - name: Completion
    directory: step_08
    has_solution: false
    