name: Lists of Content
type: flutter # Optional
steps:
  - name: ListView
    directory: list_view
    has_solution: true
  - name: Long Lists
    directory: long_lists
    has_solution: true
  - name: Separators
    directory: separators
    has_solution: true
  - name: Extract Widget
    directory: extract_widget
    has_solution: true
  - name: Material Widgets
    directory: material_widgets
    has_solution: true
  - name: GridView
    directory: grid_view
    has_solution: true
  - name: Long GridViews
    directory: long_grid_view
    has_solution: true
  - name: Conclusion
    directory: conclusion
    has_solution: false